#ifndef SCENARIOS_H
#define SCENARIOS_H

#include "../game_files/Board.h"

#include "../game_files/Decks.h"
#include "../game_files/Players.h"

#include "../game_files/Debug.h"

namespace Scenarios
{
    class Scenario{
    public:
        Scenario(std::string name,std::string desc);
        virtual ~Scenario(){};

        std::string name;
        std::string description;
        
        // generate a new board that's already setup
        virtual Board::Board* make_board(std::vector<int> roles,int _difficulty,bool verbose=false)=0;
        // Set an existing board to a state that would otherwise be generated by make_board()
        virtual void reset_board(Board::Board* game_board,bool verbose=false)=0;
    };
    
    // This is the simplest example: Use the existing setup() method and create a "normal" board.
    // Setup occurs according to the rules given in the game.
    class VanillaGameScenario: public Scenario{
    public:
        VanillaGameScenario();
        ~VanillaGameScenario(){};

        Board::Board* make_board(std::vector<int> roles,int _difficulty,bool verbose=false);
        void reset_board(Board::Board* game_board,bool verbose=false);
    };

    class ForcedDiscardScenario: public Scenario{
    public:
        ForcedDiscardScenario();
        ~ForcedDiscardScenario(){};

        Board::Board* make_board(std::vector<int> roles,int _difficulty,bool verbose=false);
        void reset_board(Board::Board* game_board,bool verbose=false);
    };

    class BusyBoardScenario: public Scenario{
    public:
        BusyBoardScenario();
        ~BusyBoardScenario(){};

        Board::Board* make_board(std::vector<int> roles,int _difficulty,bool verbose=false);
        void reset_board(Board::Board* game_board,bool verbose=false);
    };

    class CanWinScenario: public Scenario{
    public:
        CanWinScenario();
        ~CanWinScenario(){};

        Board::Board* make_board(std::vector<int> roles,int _difficulty,bool verbose=false);
        void reset_board(Board::Board* game_board,bool verbose=false);
    };
}

#endif